title: Nochat
description: Proyecto desarrollado en la asignatura de Cloud Computing desplegado en la web
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
