use Rex -feature => ['1.3'];

user "ubuntu";
private_key "/home/okynos/keys/keypair.pem";
sudo -on;

group stack => "8.43.86.216";

desc "Install dependencies for deploy some microservices (MongoDB, Mysql and RabbitMQ Servers";
task "deployServers", group => "stack", sub {
   run "sudo apt-get update";
   say "System updated";

   pkg "mongodb-server", ensure => "present";
   say "MongoDB Server installed";

   pkg "mysql-server", ensure => "present";
   say "MySQL Server installed";

   pkg "rabbitmq-server", ensure => "present";
   say "RabbitMQ Server installed";
};

desc "Install all dependencies and modules required for NodeJs execuion (NodeJs, NodeJs-dev, Npm, Socket.io and Express)";
task "deployNode", group => "stack", sub {
   pkg "nodejs", ensure => "present";
   say "NodeJs installed";

   pkg "nodejs-dev", ensure => "present";
   say "NodeJs-dev installed";

   pkg "npm", ensure => "present";
   say "Npm installed";

   run "sudo npm install socket.io";
   say "Socket.io installed";
   run "sudo npm install express";
   say "Express installed";
};
