
servers=[
  {
    :hostname => "MongoMysqlRabbitMQ",
    :ip => "IP_MACHINE_1",
  },
  {
    :hostname => "NodeJS",
    :ip => "IP_MACHINE_2",
  }
]


Vagrant.configure(2) do |config|
  # Specify the default SSH username and private key
  config.ssh.username = "YOUR_USER"
  config.ssh.private_key_path = "YOUR_KEY.PEM"

  servers.each do |machine|
     config.vm.define machine[:hostname] do |node|

       # Configure the OpenStack provider for Vagrant
       config.vm.provider "openstack" do |os|
		  
          # Specify OpenStack authentication information
          os.openstack_auth_url = "http://YOUR_AUTH_IP:5000/v2.0"
          os.username = "YOUR_OPENSTACK_USER"
          os.password = "YOUR_OPENSTACK_PASSWORD"
          os.tenant_name = "YOUR_TENANT_NAME/ID"

          # Specify instance information
          os.server_name = "vagrant-test-"+machine[:hostname]
          os.flavor = "m1.smaller"
          os.image = "Ubuntu14.04"
          os.floating_ip_pool = "public"
          os.networks = "YOUR_NETWORK"
          os.keypair_name = "YOUR_KEY_NAME"
          os.security_groups = ["default"]
          os.floating_ip = machine[:ip]
        end
     end
  end



  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "YOUR_ANSIBLE_SCRIPT.yml"
    ansible.limit = "all"
    ansible.raw_arguments = ["-i" + servers[0][:ip] + "," + servers[1][:ip] + ","]
  end

end
