
servers=[
  {
    :hostname => "Containers-Host",
    :provision => "scriptContainers.yml"
  },
  {
    :hostname => "Database-Host",
    :provision => "scriptMariaDB.yml"
  }
]

Vagrant.configure('2') do |config|
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = '~/.ssh/id_rsaAzure'
  config.vm.box = 'azure'

  servers.each do |machine|
     config.vm.define machine[:hostname] do |node|

	  config.vm.provider :azure do |azure, override|
	    azure.tenant_id = ENV['AZURE_TENANT_ID']
	    azure.client_id = ENV['AZURE_CLIENT_ID']
	    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
	    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']


	    azure.vm_image_urn = 'credativ:Debian:8:8.0.201701180'
	    azure.vm_size = 'Basic_A0'
	    azure.location = 'westeurope'
	    azure.vm_name = machine[:hostname]
	    azure.tcp_endpoints = '80:80'
	  end
     end
  end

  servers.each do |machine|
     config.vm.provision "ansible" do |ansible|
       ansible.playbook = machine[:provision]
       ansible.sudo = true
     end
  end

end
